"""empty message

Revision ID: 9bccbeb4f95f
Revises: 
Create Date: 2023-06-01 11:37:09.320349

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9bccbeb4f95f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verificacao')
    op.drop_table('listadesejo')
    op.drop_table('series')
    op.drop_table('categoria')
    op.drop_table('estabelecimento')
    op.drop_table('usuario')
    op.drop_table('filmes')
    op.drop_table('encurtador')
    op.drop_table('projetos')
    op.drop_table('googlelogin')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('senha',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('senha',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)

    op.create_table('googlelogin',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='googlelogin_pkey')
    )
    op.create_table('projetos',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('imagem', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('titulo', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('subtitulo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('texto', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tecnologias', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('link', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('github', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='projetos_pkey')
    )
    op.create_table('encurtador',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='encurtador_pkey')
    )
    op.create_table('filmes',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('imagem', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('nota', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('id_api', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('id_usuario', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], name='filmes_id_usuario_fkey'),
    sa.PrimaryKeyConstraint('id', name='filmes_pkey')
    )
    op.create_table('usuario',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cep', sa.VARCHAR(length=9), autoincrement=False, nullable=True),
    sa.Column('endereco', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('bairro', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('senha', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('telefone', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='usuario_pkey')
    )
    op.create_table('estabelecimento',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('id_categoria', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nome', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('imagem', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cep', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('endereco', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('bairro', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('numero', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('telefone', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('iniciosemana', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('finalsemana', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('horarioabertura', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('horariofechamento', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('descricao', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('produtos', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('facebook', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('instagram', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('whatsapp', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria.id'], name='estabelecimento_id_categoria_fkey'),
    sa.PrimaryKeyConstraint('id', name='estabelecimento_pkey')
    )
    op.create_table('categoria',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('imagem', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='categoria_pkey')
    )
    op.create_table('series',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('imagem', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('nota', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('id_api', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('id_usuario', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], name='series_id_usuario_fkey'),
    sa.PrimaryKeyConstraint('id', name='series_pkey')
    )
    op.create_table('listadesejo',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('imagem', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('nota', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('id_api', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('id_usuario', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], name='listadesejo_id_usuario_fkey'),
    sa.PrimaryKeyConstraint('id', name='listadesejo_pkey')
    )
    op.create_table('verificacao',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('senha', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('isvalid', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='verificacao_pkey')
    )
    # ### end Alembic commands ###
